version: '3.9'
services:
  app:
    image: "${DOCKER_USERNAME}/${DOCKER_REPO}:latest"
    container_name: catchy-server
    env_file:
      - .env
    ports:
      - "8081:8081"
    volumes:
      - ./src/resources/application-prod.yml:/config/application-prod.yml

  osrm-routed:
    image: ghcr.io/project-osrm/osrm-backend
    container_name: catchy-osrm
    ports:
      - "5000:5000"
    volumes:
      - .:/data
    command: >
      osrm-routed --algorithm mld /data/OSM/south-korea-latest.osrm