spring:
  datasource:
    url: jdbc:mysql://localhost:3306/catchy?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  h2:
    console:
      enabled: false


jwt:
  secret: ${JWT_KEY}
  accessTokenValidity: 86400000 # 1 day
  refreshTokenValidity: 604800000 # 1 week

cloud:
  aws:
    s3:
      bucket: catchy-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}

security:
  kakao:
    client-id: ${REST_API_KEY}
    client-secret: ${SECRET_KEY}