spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/catchy
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
jwt:
  secret: ${JWT_KEY}
  accessTokenValidity: 86400000 # 1 day
  refreshTokenValidity: 604800000 # 1 week