spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update # 배포 환경에서는 update
    show-sql: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 6000

  mvc:
    async:
      request-timeout: 60000

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

jwt:
  secret: ${JWT_KEY}
  accessTokenValidity: 86400000 # 1 day
  refreshTokenValidity: 604800000 # 1 week

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    region:
      static: ${S3_REGION}
    stack:
      auto: false
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}

security:
  kakao:
    client-id: ${REST_API_KEY}
    client-secret: ${SECRET_KEY}
    redirect-url: ${KAKAO_REDIRECT_URL}
    token-request-url: ${KAKAO_TOKEN_URL}
    info-request-url: ${KAKAO_INFO_URL}
  apple:
    bundle-id: ${APPLE_BUNDLE_ID}
    key-id: ${APPLE_KEY_ID}
    service-id: ${APPLE_CLIENT_ID}
    team-id: ${APPLE_TEAM_ID}
    redirect-url: ${APPLE_REDIRECT_URL}
    request-url: ${APPLE_REQUEST_URL}
    private-key: ${APPLE_PRIVATE_KEY}

map:
  tmap:
    app-key: ${TMAP_APP_KEY}
  google:
    api-key: ${GOOGLE_API_KEY}

openai:
  model: ${GPT_MODEL}
  api:
    key: ${GPT_API_KEY}
    url: ${GPT_API_URL}

osrm:
  base-url: ${OSRM_BASE_URL}

cache:
  recommended-courses:
    key: ${REDIS_CACHE_KEY}
    ttl: 604800  # 7일
  refreshToken:
    key: ${REDIS_TOKEN_KEY}
    ttl: 604800 #1주일
  blacklist:
    key: ${REDIS_BLACKLIST_KEY}

server:
  port: 8081