spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update # 배포 환경에서는 update
    show-sql: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

jwt:
  secret: ${JWT_KEY}
  accessTokenValidity: 86400000 # 1 day
  refreshTokenValidity: 604800000 # 1 week

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    region:
      static: ${S3_REGION}
    stack:
      auto: false
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}

security:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_PRIVATE_ID}
  tmap:
    app-key: ${TMAP_APP_KEY}

openai:
  model: ${GPT_MODEL}
  api:
    key: ${GPT_API_KEY}
    url: ${GPT_API_URL}

osrm:
  base-url: ${OSRM_BASE_URL}

server:
  port: 8081