spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:tcp://localhost/~/catchy
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000

  mvc:
    async:
      request-timeout: 60000

jwt:
  secret: ${JWT_KEY}
  accessTokenValidity: 86400000 # 1 day
  refreshTokenValidity: 604800000 # 1 week

cloud:
  aws:
    s3:
      bucket: catchy-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}

security:
  kakao:
    client-id: ${REST_API_KEY}
    client-secret: ${SECRET_KEY}
    redirect-url: ${KAKAO_REDIRECT_URL}
    token-request-url: ${KAKAO_TOKEN_URL}
    info-request-url: ${KAKAO_INFO_URL}
  apple:
    bundle-id: ${APPLE_BUNDLE_ID}
    key-id: ${APPLE_KEY_ID}
    service-id: ${APPLE_CLIENT_ID}
    team-id: ${APPLE_TEAM_ID}
    redirect-url: ${APPLE_REDIRECT_URL}
    request-url: ${APPLE_REQUEST_URL}
    private-key: ${APPLE_PRIVATE_KEY}

map:
  tmap:
    app-key: ${TMAP_APP_KEY}
  google:
    api-key: ${GOOGLE_API_KEY}

openai:
  model: ${GPT_MODEL}
  api:
    key: ${GPT_API_KEY}
    url: ${GPT_API_URL}

osrm:
  base-url: ${OSRM_BASE_URL}

cache:
  recommended-courses:
    key: ${REDIS_CACHE_KEY}
    ttl: 86400 #1일
  refreshToken:
    key: ${REDIS_TOKEN_KEY}
    ttl: 604800 #1주일
  blacklist:
    key: ${REDIS_BLACKLIST_KEY}